server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

jerseyClient:
  timeout: 10s
  connectionTimeout: 10s
  connectionRequestTimeout: 10s

appName: "dropwizard-kotlin example"
httpbinBaseUrl: https://httpbin.org
